# -*- coding: utf-8 -*-
#+begin_html
#+include: "../loc/es.yml"
date:   2010-01-12
layout: main
---
#+end_html
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc toc:nil

  Éstos son los artículos publicados hasta ahora:
  1. [[file:../art/computers/giga/g-es.org][Los gigas de los discos]]
  2. [[file:../art/math/logarithm/l-es.org][Logaritmos]]
  3. [[file:../art/math/power/p-es.org][Un número elevado a otro]]
  4. [[file:../art/math/six-times-nine/stn-es.org][¿Por qué es seis veces nueve igual a nueve veces seis?]]
  5. [[file:../art/math/size-paral/sp-es.org][¿Cuál es el tamaño de un paralelogramo?]]
  6. [[file:../art/math/size-triangle/st-es.org][¿Cuál es el tamaño de un triángulo?]]
* Acerca de Greater Skies
  GreaterSkies empezó como una colección /online/ de cosas que
  quiero explicar a mis hijos. Hay muchas ideas interesantes que
  descubrir, muchas relaciones que explorar, muchas intuiciones
  con que deleitarse. Quiero que descubran la fascinación de la
  comprensión súbita, y que se hagan una idea de dónde están: qué
  tamaño tienen las cosas, cómo funcionan, cómo se relacionan
  entre ellas, y dónde está esta tierra en que viven.

  No hablo sólo a sus siete y nueve años: quiero explicarles todo
  lo que me gustaría contarles, independientemente de lo complejo
  que sea, de forma que lo entiendan cuando llegue el momento.

  Muchas de las cosas de las que quiero hablar me fueron
  presentadas de formas innecesariamente complicadas o
  aburridas. Estoy haciendo un esfuerzo para encontrar las
  explicaciones más claras, las que hacen posible el flash de la
  comprensión, pero estoy destinado a fallar: soy mi propio
  varemo. No dejes de decirme lo que encuentres equivocado, o mal
  escrito, o que pueda ser explicado más claramente.

  Quiero que Greater Skies acabara siendo un proyecto
  colaborativo.  Está en [[http://github.com/juanre/Greater-Skies][github]], y lo he montado de forma que sea
  fácil añadir artículos y traducciones.  Hasta ahora solamente
  hay cosas en castellano e inglés, pero me gustaría añadir otros
  lenguajes.  Puedes contribuir de dos formas: escribe tu
  artículo o traducción y [[http://juanreyero.com][envíamelo]], o haz un /fork/ del
  repositorio =git= en github, añade lo que creas conveniente, y
  házmelo saber. 

  [[http://juanreyero.com/][Juan Reyero]], 2010-01-17
